# secrets have to be created first
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username:  dXNlcm5hbWU=
  mongo-root-password:  cGFzc3dvcmQ=
# must set values with base64 encoding. 
# Linux - echo -n 'username' | base64
# Windows - Could not find a way. Used "https://www.base64encode.org/"
